version: "2"
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct # requires every field to be instantiated in e.g. struct creation
    - gochecknoglobals
    - godox
    - gomoddirectives
    - mnd
    - varnamelen
    - wrapcheck
  settings:
    tagliatelle:
      case:
        rules:
          json: camel
          yaml: camel
formatters:
  enable:
    - gofumpt
run:
  go: "1.23"
