version: '2'
run:
  allow-parallel-runners: true
linters:
  default: standard
  enable:
#    - containedctx # ok to wrap ctx in this tool
    - contextcheck
    - dupword
#    - embeddedstructfieldcheck # only introduced in v2.2.0
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funcorder
    - goconst
    - gocritic
    - godot
#    - godox # okay to have TODO etc. in code
    - gosec
    - misspell
    - intrange
    - musttag
    - makezero
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
#    - noctx # doesn't matter for this tool
    - nolintlint
    # - paralleltest
    - prealloc
    - protogetter
    - predeclared
#    - recvcheck # this is not followed by easyjson generated files
    - thelper
    # - tparallel
    - unconvert
    - unparam
    - whitespace
    # - wrapcheck
  settings:
    goconst:
      min-occurrences: 2
      numbers: true
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cosmos/,cosmossdk.io/,github.com/cometbft/)
        - blank
        - dot
        - localmodule
      custom-order: true
      no-inline-comments: true
      no-prefix-comments: true
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    golines:
      shorten-comments: true
