name: Build

on:
  pull_request:

permissions: read-all

jobs:
  build:
    name: Build Go binary
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            flake.nix
      - name: Build binary
        run: make build
        if: "env.GIT_DIFF"
